security:
    providers:
        e2ee_cloud:
            memory:
                users:
                    admin: { password: '$2y$13$zJnQci7z.86E47vxArBj1ONu/fizxPMANa9W40B1kiICOapVs3DBS', roles: ['ROLE_ADMIN'] }
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            http_basic:
                realm: Secured Area
    encoders:
        Symfony\Component\Security\Core\User\User: 'bcrypt'
    access_control:
         - { path: ^/, roles: ROLE_ADMIN }
